SELECT
    TITLE,
    B.BOARD_ID,
    REPLY_ID,
    R.WRITER_ID,
    R.CONTENTS,
    SUBSTR(R.CREATED_DATE,1, 10)
FROM
    USED_GOODS_BOARD as B
    JOIN USED_GOODS_REPLY as R
        ON B.BOARD_ID = R.BOARD_ID
WHERE
    B.CREATED_DATE like '2022-10%'
ORDER BY
    R.CREATED_DATE, TITLE;